---
- name: My Test Playbook
  hosts: all
  become: yes
  tasks:
  - name: Install Httpd Package
    yum:
      name: httpd
      state: present
  - name: Start Httpd Service
    service:
      name: httpd
      state: started
